### ISSUE TITLE
Annoying privacy pop-up?

### ISSUE THREAD

**Issue by nicebread** [germanrepro/homepage#17]
The "We'd like to collect statistics about our visitors." pop-up appears on every new site that is opened. Can it be shown only once? 

on Safari, macos

**Comment by FelixHenninger** [comment]
Should be fixed now (as of 0805880a229e9933beb387b08517f499658c746b) -- the issue was that Matomo categorically refuses to save *any* data (including the opt-out-status), and we had to implement this ourselves. We now *do* save data even if consent is refused, but it is non-identifying and removed when the browser sessions ends.
